# Generated by Django 4.1 on 2023-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CID", models.CharField(max_length=20, unique=True)),
                ("CName", models.CharField(max_length=100)),
                ("CEmail", models.EmailField(max_length=254)),
                ("CStage", models.CharField(max_length=50)),
                ("CActrecord", models.TextField()),
                ("CStartdate", models.DateField()),
                ("CDealdate", models.DateField(blank=True, null=True)),
                ("SID", models.CharField(max_length=20)),
                ("CDemand_description", models.TextField()),
                ("CSpecial_requests", models.TextField()),
                ("CAge_range", models.CharField(max_length=20)),
                ("COccupation_category", models.CharField(max_length=50)),
            ],
        ),
    ]
