# Generated by Django 4.1 on 2023-06-04 08:34

from django.db import migrations

def create_default_data(apps, schema_editor):
    Customer = apps.get_model('finalapp', 'customer')
    Customer.objects.create(CID='112', CName='王小明', CEmail='john@example.com', CStage='準客戶', CActrecord='2023/06/04 試坐按摩椅並到店詢問', CStartdate='2023-06-04', SID='155', CDemand_description='肩頸', CSpecial_requests='無', CAge_range='21-30', COccupation_category='高級豪華型')
    Customer.objects.create(CID='133', CName='陳小華', CEmail='huaa@example.com', CStage='潛在客戶', CActrecord='2023/06/05 試坐按摩椅並加入APP', CStartdate='2023-06-05', SID='157', CDemand_description='腿部', CSpecial_requests='無', CAge_range='21-30', COccupation_category='經濟實惠型')
    
class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]

