# Generated by Django 4.1 on 2023-06-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finalapp",
            "0004_attendance_branch_coupon_couponusage_kpi_salesperson_and_more",
        ),
        ("finalapp", "0005_auto_20230606_1907"),
    ]

    operations = []
