# Generated by Django 4.1 on 2023-06-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0006_merge_20230606_1950"),
    ]

    operations = []
