# Generated by Django 4.2.2 on 2023-06-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0007_auto_20230606_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='BName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='SName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
