# Generated by Django 4.1 on 2023-06-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0012_exm_branch_smon_branch_snsale_branch_snew_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="salesdetail", name="BID",),
        migrations.RemoveField(model_name="salesdetail", name="SDate",),
        migrations.RemoveField(model_name="salesdetail", name="SDiscount",),
        migrations.RemoveField(model_name="salesdetail", name="SID",),
        migrations.RemoveField(model_name="salesdetail", name="SPay",),
        migrations.RemoveField(model_name="salesdetail", name="SPayment",),
        migrations.RemoveField(model_name="salesdetail", name="SRepurchase",),
    ]
