# Generated by Django 4.1 on 2023-06-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0013_remove_salesdetail_bid_remove_salesdetail_sdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="massagechair", name="BID",),
        migrations.RemoveField(model_name="massagechair", name="MClass",),
        migrations.RemoveField(model_name="massagechair", name="PID",),
    ]
