# Generated by Django 4.1 on 2023-06-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finalapp",
            "0014_remove_massagechair_bid_remove_massagechair_mclass_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase", old_name="PDdate", new_name="PDate",
        ),
        migrations.RemoveField(model_name="purchase", name="BID",),
        migrations.RemoveField(model_name="purchase", name="PID",),
    ]
