# Generated by Django 4.1 on 2023-06-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finalapp",
            "0016_remove_customer_cactrecord_remove_customer_cdealdate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exm",
            name="MClass",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="massagechair",
            name="MClass",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchase",
            name="MClass",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesdetail",
            name="MClass",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
