# Generated by Django 4.1 on 2023-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0017_exm_mclass_massagechair_mclass_purchase_mclass_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="profit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BID", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("one", models.IntegerField()),
                ("two", models.IntegerField()),
                ("three", models.IntegerField()),
                ("four", models.IntegerField()),
                ("five", models.IntegerField()),
                ("six", models.IntegerField()),
            ],
        ),
    ]
