# Generated by Django 4.1 on 2023-06-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0018_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="BID",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="CMON",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
