# Generated by Django 4.1 on 2023-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0019_coupon_bid_coupon_cmon"),
    ]

    operations = [
        migrations.AddField(
            model_name="massagechair",
            name="BID",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
