# Generated by Django 4.1.4 on 2023-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0020_massagechair_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=20)),
                ('Feedback', models.CharField(max_length=100)),
            ],
        ),
    ]
