# Generated by Django 4.1.4 on 2023-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0021_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfaction',
            name='Brand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
